### ISSUE TITLE
[Bug]: Package not available in NPM

### ISSUE THREAD

**Issue by tebinraouf** [microsoft/fast-cli#76]
### What happened?

Hi, 

When running the following, the package is not installed because it is not found in npm registry. 
`npm install -g @microsoft/fast-cli`

### What package(s) are causing the problem?

@microsoft/fast-cli

### Relevant log output

```shell
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@microsoft%2ffast-cli - Not found
npm ERR! 404
npm ERR! 404  '@microsoft/fast-cli@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```
```

**Comment by janechu** [comment]
Sorry for the confusion, but this is not a bug, the packages are yet to be published because we are not done with our initial alpha work.
